# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :build_deploy_prod do
    sh('flutter pub get')
    cocoapods(
      repo_update: true,
      use_bundle_exec: false,
    )
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(
      clean: true,
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
    )
    api_key = {
      key_id: ENV["FASTLANE_API_KEY_ID"],
      issuer_id: ENV["FASTLANE_API_ISSUER_ID"],
      key: Base64.decode64(ENV["FASTLANE_API_KEY_CONTENTS_BASE64"])
    }

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
